### PR TITLE
massive reducer refactor - I feel much better

### PR DESCRIPTION
**Pull request by ogroppo**

### CODE REVIEW

**Comment by ogroppo** [comment]
fixing also https://github.com/ogroppo/wikiforest/issues/3

**Comment by mshd** [comment]
Yes zoom is better but still could be stronger (less scrolling more zoom)
It seems much slower now expanding the nodes and collapsing doesn't work anymore

**Comment by mshd** [comment]
sorry didn't mean to merge it

**Comment by ogroppo** [comment]
lol, well it's meant to be merged

**Pull request merged**
